/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.11.0                                              */
/*  Date (dd.mm.yyyy): 19. 6.2022   Time (hh:mm): 19:13                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_SAIDA_OFF 29
#define GX_COLOR_ID_SAIDA_ON 30
#define DISPLAY_1_COLOR_TABLE_SIZE 31

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define DISPLAY_1_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define GX_STRING_ID_STRING_12 12
#define GX_STRING_ID_STRING_13 13
#define GX_STRING_ID_STRING_14 14
#define GX_STRING_ID_STRING_15 15
#define GX_STRING_ID_STRING_16 16
#define GX_STRING_ID_STRING_OPEN 17
#define GX_STRING_ID_STRING_CLOSE 18
#define GX_STRING_ID_STRING_ON 19
#define GX_STRING_ID_STRING_OFF 20
#define GX_STRING_ID_STRING_17 21
#define GX_STRING_ID_STRING_18 22
#define DISPLAY_1_STRING_TABLE_SIZE 23

#endif                                       /* sentry                         */
